apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: charts/test
    repoURL: https://github.com/jianrongzhang89/helm-gitops-poc.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
