apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-spring-petclinic
  namespace: openshift-gitops
spec:
  destination:
    namespace: spring-petclinic
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: argocd-example-apps
    repoURL: https://github.com/stevesea/argocd-helm-app-of-apps-example.git
    targetRevision: test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
